
-- COMANDO PARA A CRIAÇÃO DA TABELA:

CREATE TABLE tempestade (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE,
    hora_utc_1 VARCHAR2(8),
    precipitacao_mm FLOAT,
    pressao_atmosferica_mb FLOAT,
    pressao_maxima_mb FLOAT,
    pressao_minima_mb FLOAT,
    radiacao_global_kj_m2 FLOAT,
    temperatura_ar_c FLOAT,
    ponto_orvalho_c FLOAT,
    temperatura_maxima_c FLOAT,
    temperatura_minima_c FLOAT,
    temperatura_orvalho_maxima_c FLOAT,
    temperatura_orvalho_minima_c FLOAT,
    umidade_maxima_percent FLOAT,
    umidade_minima_percent FLOAT,
    umidade_relativa_percent FLOAT,
    direcao_vento_graus FLOAT,
    vento_maximo_ms FLOAT,
    vento_hora_ms FLOAT,
    cidade VARCHAR2(100),
    desastre_natural NUMBER,
    hora_utc_2 VARCHAR2(8),
    radiacao_clobal_kj_m2 FLOAT

);